include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_single_quotes: info
linter:
  rules:
    require_trailing_commas: true
    void_print: false  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: false  # Uncomment to enable the `prefer_single_quotes` rule
    unawaited_futures: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
